### ISSUE TITLE
Describe differences with wbthomason/packer.nvim

### ISSUE THREAD

**Issue by gwerbin** [savq/paq-nvim#11]
Hello! Always happy to see more Neovim package development. However, I am curious how this differs from [Packer.nvim](https://github.com/wbthomason/packer.nvim). I suspect that many other users have this same curiosity, and it might help increase adoption if users can easily make an informed decision about which package manager to use.

**Comment by savq** [comment]
Yes! That's an important idea for me, because the two projects ultimately have different goals (values?).

I tried writing some observations in the [wiki](https://github.com/savq/paq-nvim/wiki/Comparisons).

The docs already had a sort-of-comparison between Paq and some Vim8 package managers, so I also moved that to the wiki.

**Comment by savq** [comment]
I'll close the issue for now, but you're welcome to elaborate more on the things already written on the wiki.
