### ISSUE TITLE
Can I have the paq configuration outside of init.lua?

### ISSUE THREAD

**Issue by Atreyu-94** [savq/paq-nvim#113]
I would like to have a `/lua/paq.lua` file with the Paq configuration and call it from init.lua, but I can't.
The problem is that the init.lua file is starting to get long and I want to improve readability. Thanks in advance!

**Comment by einiges** [comment]
This is totally possible. But it is not possible to name that file `paq.lua` **and** have it in `…/nvim/lua/`. Because this would override the actual paq (the plugin). Think of it this way: You would call your config (*paq.lua*) with `require('paq')`, but you also call paq (the plugin) this way. That won't work.

For that reason you either need to rename your config file for example `/lua/plugins.lua` or the **highly recommended** way, move your config into a subdir. For example: `/lua/user/paq.lua`, `lua/my/paq.lua` or `/lua/atreyu/paq.lua`. Anything you want, that does not clash with your installed plugins.

From your `init.lua` you then call it with `require('user.paq')` or whatever you named it.

**Comment by Atreyu-94** [comment]
@einiges Thanks a lot!!! I got it! :) Right now I can to order everything. I love the simplicity of Paq. I tried Neovim before, but the complexity of Packer make me change to GUIs again. Now I can install plugins without uggly issues.
