### ISSUE TITLE
Add commit to options

### ISSUE THREAD

**Issue by victorklos** [savq/paq-nvim#114]
Thanks for paq!

My `nvim` lags behind slightly as I am running Debian testing. This makes package updates fail sometimes. Now I could manage specific package state directly in git, and then pin it in paq. However, it would be nicer to add a `commit hash` option and have paq manage such pinning details.

Would you be willing to consider this? I am new to lua but not to programming and would be happy to create a PR.

**Comment by Ttibsi** [comment]
Taking a quick breeze through the code, I wonder if we can add something similar here: https://github.com/savq/paq-nvim/blob/2101c710b712df9569873f1dae7815a4a5c18194/lua/paq.lua#L101

At the very least, we add a `pkg.commit` or something and then append to the `clone` command something like `&& git -C nvim-treesitter checkout pkg.commit`. A quick google shows that it may not be able to do the same thing you're doing there (using --branch) for a speciic hash, so just appending the checkout command is probably the easiest way to do this. 

I don't know how to go about testing this, or otherwise I'd be happy to put in a PR for this - what would you suggest?

**Comment by savq** [comment]
There's no way to do a clone (shallow or not) of a specific commit. However, you can pass a tag to `git clone --branch`,
so the `branch` argument in Paq can also take a tag.

For the specific case of nvim-treesitter, I've opened https://github.com/nvim-treesitter/nvim-treesitter/issues/3915 to request the addition of such tags, since I think "official" nvim plugins should be setting the example of good versioning practices.

**Comment by Ttibsi** [comment]
Agreed that this is a PITA that’s nvim-treesitter’s fault. Checking out a specific commit is the best thing I can think of to get around. I’m not sure if what my PR is trying will work this out tho

**Comment by victorklos** [comment]
From what I understand this is no longer needed. Closing.

**Comment by victorklos** [comment]
From what I understand this is no longer needed. Closing.
