### ISSUE TITLE
PaqClean command removes all packages except paq-nvim

### ISSUE THREAD

**Issue by craigmac** [savq/paq-nvim#130]
Running `PaqClean` removes everything I had just installed with the exception of paq-nvim. Help says that clean is supposed to remove packages found on paq-dir that aren't listed in your configuration. How do I tell which ones are 'listed in your configuration'?

in init.lua:

```lua
local path = vim.fn.stdpath('data') .. '/site/pack/paqs/start/paq-nvim'
local first_install = false

if vim.fn.glob(path) == "" then
  first_install = true
  vim.fn.system({ 'git', 'clone', 'https://github.com/savq/paq-nvim', path })
  vim.cmd.packadd('paq-nvim')
end

local packages = {
  'savq/paq-nvim',

  'tpope/vim-commentary',
  'tpope/vim-repeat',
  'tpope/vim-unimpaired',
  'tpope/vim-surround',
  'tpope/vim-markdown',
  'tpope/vim-fugitive',
  'tpope/vim-rhubarb',
}

local paq = require('paq')
if first_install then
  print('Paq: first install, plugins being installed, if prompted hit Enter to continue.')
  paq(packages)
  paq.install()
end
```

When plugins are done installing, run `:PaqClean` and they will all be removed. Even if you restart immediately after installing them all, then run `:PaqClean`, it removes them all (with exception of paq-nvim itself). I hit this bug because I had setup this autocmd, that I finally realized was removing my packages:

```lua
vim.api.nvim_create_autocmd('BufWritePost', {
  command = 'PaqClean | PaqInstall',
  group = vim.api.nvim_create_augroup('Paq', { clear = true }),
  pattern = vim.fn.expand('$MYVIMRC'),
})
```

**Expected Behaviour:**
None of the packages listed in my `packages` variable are removed from filesystem.

**Environment:**
 - `nvim --version`: HEAD
- `git --version`: 2.37.1
- OS: macOS 12.6

**Comment by savq** [comment]
Hmmm, there's two separate things going on here:

1. You're assigning to the variable `packages`, but you only pass `packages` to paq on a first install. You could:
- Put the line `paq(packages)` before the conditional, ensuring the list of packages always gets read by Paq.
- Put the line `local paq = require('paq')` inside the conditional (but you'd have to import paq manually to update stuff).

You can always double-check by running `:PaqList`.

2. Paq doesn't delete itself because people sometimes didn't put paq in their list of plugins. Deleting everything (including Paq) was the original behavior, but some people thought that was a bug...

**Comment by craigmac** [comment]
Thanks, I did figure it out by doing exactly what you said in the first point: I just added another pack(packages) and then ended up condensing into:

```lua
local paq = require('paq')
paq(packages)
paq.install()
if first_install the print('...') end
```
I'll close this as solved, thanks for the help!
