### ISSUE TITLE
What neovim version is paq trying to target?

### ISSUE THREAD

**Issue by saccarosium** [savq/paq-nvim#148]
I've been planing to do a PR to lean the code and address some of the `TODO` in the source. But I was wondering what Neovim version you are trying to target, since I've seen checks for `nvim 0.6.0`. For reference on the latest release of Debian (12 Bookworm) ships with `neovim 0.7.2-7`, in my opinion we can safely assume a user will use that version or higher.

**Comment by savq** [comment]
> I've been planing to do a PR to lean the code and address some of the TODO in the source.

That'd be great Luca. Contributions are always welcome.

> For reference on the latest release of Debian (12 Bookworm) ships with neovim 0.7.2-7

Following Debian stable's version of neovim sounds very reasonable. That could be written down in the docs, so users know when to expect changes.

Originally I was planning to have Paq major versions match nvim minor versions. But that never happened, because Paq doesn't change that often. Still, If we're going to update the minimum requirements, might as well do the other pending breaking changes.

The ones I had listed in my notes are:

* Use lua for command and autocmd defintions.
* Remove redundant `paq` export. Keep `register`.
* Rename `run` option to `build`.
  - There's been issues with people thinking it's meant to store a plugin's config.
  - I also want to rename the `call_proc` function to `run` ([like in Julia](https://docs.julialang.org/en/v1/base/base/#Base.run))
  - To match lazy.nvim?

There's also a TODO mentioning `vim.fs`, but that requries nvim 0.8.

**Comment by saccarosium** [comment]
Closing since answered.
