### ISSUE TITLE
I can't get paq-nvim to work after following all the instructions. 

### ISSUE THREAD

**Issue by fmotion1** [savq/paq-nvim#155]
**Describe the bug**

I can't get it to work. I installed neovim and followed the guide [here](https://github.com/nanotee/nvim-lua-guide). When I type `:source %` I get `E499: Empty file name for '%' or '#', only works with ":p:h"`

![ubuntu_D2DIHpsx2F](https://github.com/savq/paq-nvim/assets/33441569/858aeb2f-3dcf-4756-a75d-9d8586c51ca1)

My `init.lua`:

```lua
require "paq" {
    "savq/paq-nvim", -- Let Paq manage itself

    "neovim/nvim-lspconfig",

    { "lervag/vimtex", opt = true }, -- Use braces when passing options

    { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' },
}
```

**To Reproduce**

1. Install neovim
2. Run `git clone --depth=1 https://github.com/savq/paq-nvim.git \
    "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/pack/paqs/start/paq-nvim`
3. Create your `init.lua`, and populate it with the contents on the install page.
4. Open neovim and type `source: %`

**Expected behavior**
The paq manager should install plugins listed in the `init.lua` file.

**Environment:**
 - `nvim --version`: 0.6.1
- `git --version`: 2.34.1
- OS: Ubuntu in WSL2 running on Win10 Pro x64.

Any help greatly appreciated!

**Comment by savq** [comment]
In ex commands, the character `%` is replaced with the name of the current file name (see [`:help cmdline-special`](https://neovim.io/doc/user/cmdline.html#cmdline-special)).

The Usage section of the README assumes you have your `init.lua` open when running the command. It's probably a good idea to suggest `:source $MYVIMRC` instead, since it'll work regardless of the current file.

Also, the idea of running `:source` is reloading your config without closing nvim. If you open and close nvim, you don't have to run `:source`, since Paq will already be loaded.
