### ISSUE TITLE
question: how do i make a package require another package?

### ISSUE THREAD

**Issue by shebangcode** [savq/paq-nvim#162]
is it even possible?

**Comment by saccarosium** [comment]
Hello @shebangcode,
No, it is not possible.

Paq doesn't manage neither the `runtimepath` nor the loading of the packages. It instead rely on the `packages` features, so it is vim that deals with the loading of the packages. For this reason we don't have a concept of dependencies, since such concept is only useful when the package manager manages the loading of the packages, so when it loads a package it will load also its dependencies. 

For this reason dependencies are treated like every other package:

```lua
-- with lazy.nvim
{
  "folke/noice.nvim"
  dependencies = {
    "MunifTanjim/nui.nvim",
    "rcarriga/nvim-notify",
  }
}

-- with paq-nvim
require("paq") {
  "folke/noice.nvim",
  "MunifTanjim/nui.nvim",
  "rcarriga/nvim-notify",
}
```

**Comment by shebangcode** [comment]
Oh, ok. Thank you very much for the answer!

Le lun. 1 janv. 2024 à 20:46, Luca Saccarola ***@***.***> a
écrit :
