### ISSUE TITLE
Hide "Nothing to install" message on startup

### ISSUE THREAD

**Issue by Supreeeme** [savq/paq-nvim#164]
When starting up neovim and there are no packages for paq to install, paq will print a "Nothing to install" message on startup. Would there be a way to hide this message? I'd like it to be shown if there are things to install, but print nothing otherwise.

**Comment by savq** [comment]
You might be running `paq.install()` or `paq.sync()` at startup.

You could put that code inside a conditional so it doesn't always run, or you could run `paq.update()`, which won't try to install things (so it never shows that message).

**Comment by Supreeeme** [comment]
I do run `paq.install()` at startup. Is there a straightforward way of determining if there are actually new packages to install?

**Comment by saccarosium** [comment]
Currently there is not a easy way to get that. But we could do one of two things:
1. having a 'statusline' component like `lazy.nvim`.
2. expose a paq method (something like `paq.query`) to be able to call the [`filters table`](https://github.com/savq/paq-nvim/blob/b2643f77461c46aa7bd7d3407d67e312483c24a5/lua/paq.lua#L48-L56) directly. Obviously the returning table will be deepcopys to not mess up the internal state of paq.

Personally I like the second approach because is more in paq's spirit of doing things.

**Comment by saccarosium** [comment]
Hey @Supreeeme,
you can now do this with the new `paq.query` method:

```lua
vim.api.nvim_create_autocmd("VimEnter", {
	once = true,
	callback = function() 
            local pkgs_count = #require("paq").query("to_install")
            if pkgs_count < 1 then return end
	    vim.notify(string.format("There are %d to install", pkgs_count))
	end
})
```

**Comment by Supreeeme** [comment]
Works like a charm, thanks!
