### ISSUE TITLE
Add a `PaqList` command

### ISSUE THREAD

**Issue by savq** [savq/paq-nvim#21]
Besides listing the packages, it should have a marker to indicate if an
operation has performed. `+` for installs, and `*` for updates.
Packages that fail to parse should not be listed.

Still undecided on whether uninstalled packages should not be listed,
or if the should have a marker like `-`.

This doesn't substitute the existing prompt messages.

**Comment by bR3iN** [comment]
I think if `PaqList` reflects recent installations and updates, it makes 
sense to also list recent uninstallations.

However, just adding a `-` might be confusing if people don't expect an 
uninstalled  package to be listed at all since it could also mean something 
like "tagged for uninstallation" or something similar. Maybe it would be 
better to list uninstalled packages separately, for example as

```
Installed plugins:
   *dracula
   +nvim-compe
   *vimtex
    ...
Recently removed:
    nvim-completion
```
