### ISSUE TITLE
Install local `paq` plugins?

### ISSUE THREAD

**Issue by megalithic** [savq/paq-nvim#25]
Hey there @savq!

I was wondering if it was possible to point to local filesystem for in-development plugins? 

Thanks!

**Comment by savq** [comment]
You can change the directory where Paq downloads stuff with the `setup` function, but that won't change neovim's runtime path.

Under`.local/site/nvim/pack`, I keep three directories:

- `paqs`, the usual paq-directory
- `local`, where I put the plugins I develop
- `test`, where Paq puts plugins when running the "test" suite

I have my term-multiplexer set-up so I can open new a terminal in `.local/site/nvim/pack/local/start`, and get to work quickly.

The only risk with putting your plugin in `paqs` is that if it isn't listed in your config, Paq _will_ delete it. Once I accidentally let Paq delete itself that way, without pushing the latest commits, true story. 🤦‍♂️

**Comment by aca** [comment]
+1 for something like `paq '~/vim/personal'`
Maybe can we just create symbolic link when local filesystem is used?

**Comment by megalithic** [comment]
👍 to this idea.

**Comment by savq** [comment]
I was a bit busy when I wrote the first answer so that was phrased wrong.

My point was that Paq doesn't modify the `runtimepath`, and there are easier ways to track a local plugin, namely:

-  Add it to a directory in `packpath` (different from the one Paq uses)
- Modify the `runtimepath` directly

I sorta explained the first option in the first comment (at least how I use it), but honestly, the best way to understand is to read `:h packages`.

The alternative, just requires you to concatenate the path to the plugin to your `runtimepath`:

```lua
vim.o.runtimepath = vim.o.runtimepath .. ",~/vim/personal"
```

Yes, it looks clunky because Lua doesn't have a concat-assignment operator (you can write it in VimL if you prefer), but it is a one liner solution that doesn't require adding anything to Paq.


-------

> Paq is best plugin manager. Thanks @savq

I wish. Thank you for using it 😄

**Comment by megalithic** [comment]
Thank you so much @savq !! Learned a lot with this!

**Comment by megalithic** [comment]
@savq it might be worth adding a small blurb to this explanation you gave on the readme.

**Comment by savq** [comment]
I've added this to the docs. Gotta keep that readme lean.
