### ISSUE TITLE
Lazy plugin loading

### ISSUE THREAD

**Issue by jc00ke** [savq/paq-nvim#26]
For heavy plugins like [tpope/vim-rails](https://github.com/tpope/vim-rails) it would be lovely to have a [lazy option](https://github.com/junegunn/vim-plug/blob/cffcfe150bda75177920530c5f1911b52f70a065/plug.vim#L328) like `plug`. Any interest in this feature? Thanks!

**Comment by savq** [comment]
No, it's unlikely I'll add this, I'm sorry.

It's worth noting that vim-plug's own lazy loading does [very little](https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option). In particular, vim-rails defines most of it's logic in the `autoload` directory (in a single file… but whatever), so it shouldn't increase start-up time much. 

Since Vim8 (and neovim) there's also a built-in way to lazy load the entire plugin (`:h packadd`). You can use that with an autocommand if you want. Unfortunately, neovim doesn't have a way to define autocommands in Lua (see neovim/neovim#12378).

-----
**Alternative solution:** Declare vim-rails as an optional plugin, and define an autocommand for it

```lua
paq {'tpope/vim-rails', opt=true}
vim.cmd [[autocmd Filetype ruby packadd! vim-rails]]
```

**Comment by jc00ke** [comment]
Makes sense, and thanks for the pointers! :pray:
