### ISSUE TITLE
Installing non existent packages causes weird buffer mangling

### ISSUE THREAD

**Issue by karbica** [savq/paq-nvim#32]
I found this issue by accident. If I add a package, that does not exist on GitHub, to be installed by `paq` the current line of the buffer will be replaced with a `Username for https://github.com':` text.

Illustrated on line 28 of the screenshot.

![Screen Shot 2021-04-16 at 7 17 58 PM](https://user-images.githubusercontent.com/8563742/115099159-f716cd00-9ee8-11eb-9f3d-53268f233fe3.png)

I intended to install the package `kjssad/quantum` but it was actually `kjssad/quantum.vim`. Attempting to install the former is what caused this issue. It also locks up user input taking a while to exit.

The solution here is obviously to install packages that exist but gracefully failing when the package doesn't exist would be nice.

**Comment by savq** [comment]
Paq clones packages via HTTPS (instead of [SSH or some other protocol](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols)) , since you don't really need write permissions. Still, if you haven't set up git to cache your credentials, it'll complain when you try to clone a repo from github.

See [Why is Git always asking for my password?](https://docs.github.com/en/github/getting-started-with-github/why-is-git-always-asking-for-my-password)

Also see #4

**Comment by karbica** [comment]
That all makes sense. But that's not what this issue is addressing.

This issue is about the buffer getting mutated where the cursor is when a non existent package is attempted to be installed. On line 28 you can see the text about the username. Why is it writing text to my buffer? It should have asked as that a prompt in the command line.

**Comment by savq** [comment]
I haven't been able to reproduce the buffer changing. Paq doesn't write to buffers, it always write to stdin.

Paq _does_ assume git processes won't wait for user input, that's what credentials must be set before using it. And if that condition is met, it'll just write `paq [n/n] failed to install foo`.

**Comment by DFreds** [comment]
I was also able to reproduce this. In a buffer, I did a PaqInstall and accidentally had `'nvim-lua/plenary';` instead of `  'nvim-lua/plenary.nvim';`. Wherever my cursor was in the buffer, it put in Username for https://github.com': text and locked up the instance of neovim. Not a huge deal.... but I could see it tripping up people if they make any minor mistakes on the plugins.
