### ISSUE TITLE
Cross-file plugin registration gone

### ISSUE THREAD

**Issue by 3nuc** [savq/paq-nvim#47]
Ever since upgrading to the last version calling `Paq'some/plugin-here'` doesn't work. I've seen the README.md and that this syntax is deprecated

In my dotfiles I expose `Paq=require 'paq-nvim'.paq` as a global variable (notice how it's not `local Paq` but just `Paq`) - https://github.com/3nuc/dotfiles/blob/master/.config/nvim/init.lua#L6

Then, thanks to the new neovim 0.5 "runtime files" feature: https://github.com/nanotee/nvim-lua-guide/blob/master/README.md#runtime-files, I can put plugin-related files in eg. `plugin/telescope.lua` then register all the telescope-related plugins using Paq there:
https://github.com/3nuc/dotfiles/blob/master/.config/nvim/plugin/telescope.lua#L2-L7

The problem is that with the newest version of paq this is not supported, as I get a bunch of errors when launching recently (but it works with v7) and the only way to register plugins is registering them all at once in a big dictionary? As seen in the maintainer's config: https://github.com/savq/dotfiles/blob/master/nvim/init.lua#L16

Wasn't paq unique in the regard that you could register a plugin anywhere? I see Vundle, packer etc. all have a

```
packer#begin
packer'someplugin'
packer'someplugin'
packer'someplugin'
packer#end
```
syntax 

I forked and reverted to v7 here: https://github.com/3nuc/paq-nvim. I could probably use the paq branch= command but I wasn't really sure if it supports tags (releases)

**Comment by 3nuc** [comment]
Hmm it'd potentially be possible to keep cross-file registration if I made a global dictionary, then append each plugin to that dictionary. After all the plugins are there, try calling `paq(plugins)` from an `after/` folder runtimefile?

**Comment by 3nuc** [comment]
Yep that works, it's a little more complex: https://github.com/3nuc/dotfiles/commit/64870a66cddfb1e708198188f182a6667392f6db

**Comment by savq** [comment]
I think the problem was unrelated to the old declaration syntax. See #49.

I know the old declaration syntax had advantages. That's why I wrote it like that in the beginning. The goal when changing how Paq worked was to make state less of a problem. With older versions of Paq, you'd have to restart the editor to update the list of packages. Now, resourcing your config should be enough.

I don't have a reason to remove the old declaration syntax, so it'll stay in Paq for now.

The alternative you suggest to make the new system behave more like the old one should also work. Note that the `Plugins` doesn't need to be global, since `PaqAdd` will close over it.
