### ISSUE TITLE
PaqSync command

### ISSUE THREAD

**Issue by mastertinner** [savq/paq-nvim#51]
It would be great to have a `PaqSync` command just like `PackerSync` as described here: https://github.com/wbthomason/packer.nvim#quickstart

This command would be equivalent to first running `PaqInstall`, the `PaqClean` and then `PaqUpdate`.

Furthermore, it would be nice to have a `PaqSync!` command that runs the whole thing non-interactively to make it easier to use in automation scripts.

**Comment by savq** [comment]
Adding `PaqSync` is really easy, but using it non-interactively isn't, for some very annoying reasons.

The `libuv` wrapper that neovim uses has a very unstructured async mechanism. You can pass callbacks to an async operation, but you can't await/return values. It's just callback hell.

Paq deals with this by… not dealing with it. There are callbacks to print back info to the prompt, but the logic to check whether all operations are finished is very limited. So if you were run
```sh
nvim --headless -c 'PaqSync'
```
There would be no way to assert that all updates have completed (so that it quits and continues with the rest of a script or whatever).

Packer does have it's own async library to deal with this, so these limitations aren't be a problem there, but I don't know if there are ways to expose it to the user.

Plenary also has utilities for async operations, and I'd be great if these were added to core Neovim.

Since Paq is about using built-in features and keeping a small feature set (for better or worse), I think this is out scope.

**Comment by mastertinner** [comment]
Thanks, @savq for implementing the `PacSync` command so quickly and thoroughly explaining the reasoning about non-interactive commands!
