### ISSUE TITLE
Prevent hanging by git command on mis-typed repository

### ISSUE THREAD

**Issue by DarwinSenior** [savq/paq-nvim#57]
Hi, 
I was wondering if we can have `GIT_TERMINAL_PROMPT=0` by default to prevent hanging by mistyped git repository?
Usually if you type the repo names wrong, the nvim will hang by requesting you to typing username and password

**Comment by savq** [comment]
Man, I tried to do this several times, and apparently the problem was that I was passing a table to `env`, but you're supposed to pass a list of strings (wtf luv?) Anyways, this issue reminded me to look again, and I saw that nanotee had fixed this in Packer a while ago.

This was a very common complain so thank you so much 🙌

**Comment by windwp** [comment]
hi, I want to use an ssh URL to clone.
@savq 

sample 
```lua
require "paq" {
    "savq/paq-nvim";          
    {"windwp/nvim-autopairs",  url='git@github.com:windwp/nvim-autopairs.git'}.
}
```
but it will tell me I have the wrong permission for my public key. I am very sure my key has correct permission.

I try to remove that GIT_TERMINAL_PROMPT=0  from paq code then I can clone my repo using ssh method.

so can we only add that environment variable only on http method?
Thank.
