### ISSUE TITLE
Feature Request: usage with nvim-notify

### ISSUE THREAD

**Issue by kiuKisas** [savq/paq-nvim#65]
It could be awesome to have a notification when adding a package or update it, through https://github.com/rcarriga/nvim-notify.
As far as I understand, you can use `vim.notify` to handle it.

**Comment by eric-hansen** [comment]
I think this would better be served with a pre-post hook of some sort, because at the same time it will spawn a new notification for each plugin, and if you end up installing or syncing (or what have you) like 20 plugins, you'll have a lot of clout on the window and loose information.

**Comment by savq** [comment]
I'm working on improving the output messages. I can use `vim.notify` since that's part of neovim since 0.5. That rework probably also includes defaulting the `verbose` option to `false`, meaning messages like `Paq [n/n] (up-to-date) foo` won't show up, hopefully reducing the "spamminess".

> I think this would better be served with a pre-post hook of some sort for someone to wire it up themselves.

Yes, that's how `vim.notify` works. If a users wants to use the linked plugin they can do that, otherwise the default handler will just print a message, same as it has always worked.

I should note that the linked repo has a bunch of extra features that wouldn't be supported because they're not part of the `vim.notify` spec.

`<rant>`
that plugin assumes gui colors, dark backgrounds, and uses unicode private use area characters (nerdfonts probably) by default, which is just… not great, and makes me even more averse to supporting it.
`</rant>`

**Comment by savq** [comment]
Paq now has support `vim.notify`.

It also defaults to `verbose=false`. so trivial messages like `(up-to-date) foo` won't show up unless the user opts in.
