### ISSUE TITLE
Different way to display updated plugins

### ISSUE THREAD

**Issue by ckipp01** [savq/paq-nvim#8]
Firstly, thanks for this great simple plugin. This was exactly what I was looking for in a nvim package manager.

I'm curious what your thoughts are on displaying the output of `:paqUpdate` a bit differently. Now it just seems to run through all of your plugins, and show a brief message that `Paq [10/10] pull changes for plugin`. It doesn't really give any indication tot he user what was actually updated. I noticed that the `:paqClean` actually tracks which plugins were removed and lists them. Would you be open to having something similar for `:paqUpdate`?

**Comment by savq** [comment]
Hi,

The intent of the latest release was to make the messages for each operation clearer. The way updates work hasn't changed, Paq runs `git pull` for all plugins, but before Paq just printed `update foo` regardless of whether the plugins changed or not, right now, well… it still does that, but explicitly.

Checking updates is a bit trickier than checking removals because it requires capturing the output of each `git pull`. This is kind of related to #7, and a previous comment in #2 suggesting capturing the commit log.

I'm working on a few other things, so these days I'm not going to be super attentive to Paq, but I'll try not to delay this much.
