### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by maxdevjs** [savq/paq-nvim#83]
Hello, I use `Paq` and I have no complaints: it does everything I need, I think that it is amazing.

Nonetheless, I wonder if it is/will still be active.

Best wishes

**Comment by astier** [comment]
@savq I subscribed to this issue. If you post your blog post let us know by linking it here so we get a notification.

**Comment by danshumaker** [comment]
I'm loving Paq.  It's simplicity&speed is the way to go!!  The only thing I wanted (wish) is to have a command like  "PaqVSync"  for verbose syncing.  When I used to use Plug I liked the verbose output of what libraries/plugins/packages were getting updated.   I created this little function to do what I thought was necessary but since PaqSync is asynchronous the last PaqLogOpen opens the cleaned log before sync has actually run... So the Verbose syncing doesn't really work as I intended.
![2021-11-24_09-50-41](https://user-images.githubusercontent.com/358833/143260655-2da558d7-34da-484b-a98b-107f844ce7e8.png)

So if there is a way to automatically open the Paq log after the PaqSync has completed that would be great to know (and do).

**Comment by savq** [comment]
I decided to make a [1.0 release](https://github.com/savq/paq-nvim/releases/tag/v1.0.0) so that people know the current features are mostly stable and won't change in the near future.

I also added a bug report template. Hopefully I'll be able to fix bugs in a more timely manner.

**Comment by savq** [comment]
@danshumaker I'll probably won't add your suggested feature, but you might be able to achieve something similar using autocommands. like:

```vim
PaqLogClean
autocmd User PaqDoneSync PaqLogOpen
```

**Comment by savq** [comment]
I'll close this since the answer for the past 2 years has been "Yes. It's active, but not much."

Near future developments are tracked in #149
