### ISSUE TITLE
THANK YOU and a question about the mechanics

### ISSUE THREAD

**Issue by megalithic** [savq/paq-nvim#9]
@savq thank you so much for this plugin. it works incredibly well! the post-install hook is brilliant.

one question though; just something i noticed in your own dotfiles and it got me wondering about some of the mechanics of how these plugin managers work (in a lua world?)..

i noticed you don't ever actually source/require/load your packages.lua in your dotfiles; i'm assuming you open them once; packadd call in there loads packer from runtimepath where you cloned it, then you can run PaqInstall or whatever you need, and that's it. You don't ever need to source your packages again.. How do we know a plugin that is installed with paq is sourced/loaded to then set their config via lua too?

**Comment by savq** [comment]
> @savq thank you so much for this plugin.

I'm glad you find it useful!


> i noticed you don't ever actually source/require/load your packages.lua in your dotfiles…

You're right, I don't source Paq on startup; like you said, I only do it when updating stuff. Using my [dotfiles](https://github.com/savq/dotfiles/tree/master/nvim) calling `:lua require 'packages'` is enough to update everything.

Of course, Paq can also be used as usual in an `init.vim` / `init.lua`. You'd need _a ton_ of packages to affect start up times.


> How do we know a plugin that is installed with paq is sourced/loaded to then set their config via lua too?

That's a pretty good question because… it depends. The vim component of a plugin works as usual (plugin, autoload, etc), and these plugins usually set global variables to avoid reloading, you can use those to know if the plugin is loaded. The Lua part of a plugin is never sourced automatically, so an all-Lua plugin is only loaded if you call `require`.

 Lua has a special table `package.loaded` that lists all modules (and submodules) that have been defined, so to be sure `foo` was sourced you'd have to do:

```lua
if not package.loaded['foo'] then
    require('foo')
end
```

My dotfiles actually leverage that table, because that's how Plenary "reloads" packages, by nulling the entry in the `package.loaded`.

This question also made me realise there was a small mistake in my dotfiles. I was calling `require 'paq-nvim'` before calling `reload_module`. So that's also fixed now, thanks 👍
